name: test
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo@sha256:49f1d7b87c2ddf918372be5defe7edff8c46703d0b2a56023a3f825e32e1250c
        ports: ["27017:27017"]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm ci
      - run: npm test
