name: test
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo@sha256:20f3adcaffe2193e49dd502c8299b770d49a1e0643e0e9db250d5c127b1e9ed8
        ports: ["27017:27017"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm ci
      - run: npm test
